[program:gunicorn]
command=/usr/bin/gunicorn run:app -b localhost:5000
directory=/app
autostart=true
autorestart=true
stdout_logfile = /app/logs/gunicorn/gunicorn_stdout.log
stderr_logfile = /app/logs/gunicorn/gunicorn_stderr.log
redirect_stderr = True
environment = PRODUCTION=1
